language: generic
branches:
  only:
  - master
  - "/^v.*$/"
jobs:
  include:
  - os: osx
    language: generic
    before_install:
    - brew update
    - brew upgrade python@2
    - pip2 install virtualenv
    - python2 -m virtualenv env
    - source env/bin/activate
  - os: osx
    language: generic
    before_install:
    - brew update
    - python3 -m venv env
    - source env/bin/activate
  - services: docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    install: bash .manylinux.sh
    script: true
  - services: docker
    arch: arm64
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
    install: bash .manylinux.sh
    script: true
  - services: docker
    env:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    - PRE_CMD=linux32
    install: bash .manylinux.sh
    script: true
install:
- pip install --upgrade pip wheel
- pip install .[test]
- python setup.py bdist_wheel
script:
- python setup.py test
deploy:
  provider: releases
  token:
    secure: LLIpsqiZ8qSKoUpxJYmlDx4vhVGe3akQdrbWEyY3cNA/ixN7MTjCyYrCGNAv85GM2Z5coIt/KVJxYDigMLTrw/geJwsNInFZnWlwT627p9CCaH3hXT2P/Fk8jwCGycgUDkPppGYrWXTfy82OZi9LtbDYYP5r6TP/oz4hr7HwlYrk7udEItuWKiqSpyZT1QvRHTWZ24YOCxCq7krMfSdlwtwJS1htbIgQL6x7ZKIeKcp+KT0Omp8mVzbspoG3XUklQmzLIrkh0kemEnEktnOgGHiCUGW95YeO5SiMthiov7YM1t4hKSqmplizjJOhkhkaGP3Wq8tDzAG4Q73+bPZWeDN+Xj3cY7J+4ahWH8CnBe0jV50UbwL5kpPoM4zx+KFNNsYSE0GYoZN2eCcdwmsO4D3eI7KfS+0Ik2p1Uf27q9HiDYN40KyHrEKlGSRKqPb9c7Tj8ad1pWJxdmC6AyDPxvK8j3VDKdUoS3tsSxuJSgpyiTs5yMHbOorbT+h5R2ro56GeNknhCrbFSt64k5eBnYxG5brmwUJB+Ift4WNCr2H5soq0Js2npDJg1BDZb5/viiEftATWsL34C0k+zaw3vzPY0G3ProBHfsYnkjmYupNo2JiPIHte+cI0yLOGihcIB3C/cefQzSxAnGOh+Ws5SD7993zejXkDasROi7mGCqQ=
  file_glob: true
  file: dist/fastcluster*.whl
  cleanup: false
  on:
    repo: dmuellner/fastcluster
    tags: true
